{% set name = "os-client-config" %}
{% set version = "2.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e16a260f2fd500af14f157b9b7b7d69292ce83b0f8a461ec68ce6a8a42967cbd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pbr >=2.0.0
    - setuptools

  run:
    - python >={{ python_min }}
    - openstacksdk

test:
  requires:
    - python {{ python_min }}
  imports:
    - os_client_config
    - os_client_config.tests

about:
  home: https://docs.openstack.org/developer/os-client-config/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'OpenStack Client Configuration Library'
  dev_url: https://git.openstack.org/cgit/openstack/os-client-config
  doc_url: https://docs.openstack.org/developer/os-client-config/

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
