{% set name = "os-client-config" %}
{% set version = "1.31.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "b60283d73175ab2f55eef894e890f51125ac01442545364f5ddb6d55f8ad27fc" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - pyyaml >=3.1.0
    - appdirs >=1.3.0
    - keystoneauth1 >=2.1.0
    - requestsexceptions >=1.1.1

test:
  imports:
    - os_client_config
    - os_client_config.tests

about:
  home: https://docs.openstack.org/developer/os-client-config/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'OpenStack Client Configuation Library'
  dev_url: https://git.openstack.org/cgit/openstack/os-client-config
  doc_url: https://docs.openstack.org/developer/os-client-config/

extra:
  recipe-maintainers:
    - pmlandwehr
