{% set name = "os-client-config" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abc38a351f8c006d34f7ee5f3f648de5e3ecf6455cc5d76cfd889d291cdf3f4e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
    - pbr >=2.0.0

  run:
    - python >=3.6
    - openstacksdk

test:
  imports:
    - os_client_config
    - os_client_config.tests

about:
  home: https://docs.openstack.org/developer/os-client-config/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'OpenStack Client Configuration Library'
  dev_url: https://git.openstack.org/cgit/openstack/os-client-config
  doc_url: https://docs.openstack.org/developer/os-client-config/

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
